<div>
    <table class="border-collapse table-auto w-full whitespace-no-wrap bg-white table-striped relative">
        <thead>
        <tr class="text-left">
            <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-2 text-gray-600 font-bold tracking-wider uppercase text-xs">
                ID
            </th>
            <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-2 text-gray-600 font-bold tracking-wider uppercase text-xs">
                Height
            </th>
            <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-2 text-gray-600 font-bold tracking-wider uppercase text-xs">
                Timestamp
            </th>
            <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-2 text-gray-600 font-bold tracking-wider uppercase text-xs">
                Transactions
            </th>
            </th>
            <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-2 text-gray-600 font-bold tracking-wider uppercase text-xs">
                Generated by
            </th>
            </th>
            <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-2 text-gray-600 font-bold tracking-wider uppercase text-xs">
                Forged
            </th>
            <th class="bg-gray-100 sticky top-0 border-b border-gray-200 px-6 py-2 text-gray-600 font-bold tracking-wider uppercase text-xs">
                Fee
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach ($blocks as $block)
            <tr class="hover:bg-gray-200">
                <td class="border-dashed border-t border-gray-200 userId">
                    <span class="text-blue-500 px-6 py-3 flex items-center cursor-pointer"
                          wire:click="showDetails('{{$block['id']}}')">
                                {{ $block['id']}} </span>
                    </span>
                </td>
                <td class="border-dashed border-t border-gray-200 height">
                    <span class="text-gray-700 px-6 py-3 flex items-center">
                        {{ $block['height']}} </span>
                    </span>
                </td>
                <td class="border-dashed border-t border-gray-200 timestamp">
                    <span class="text-gray-700 px-6 py-3 flex items-center">
                        {{ $block['timestamp']}} </span>
                    </span>
                </td>
                <td class="border-dashed border-t border-gray-200 transactions">
                    <span class="text-gray-700 px-6 py-3 flex items-center">
                        {{ $block['transactions']}} </span>
                    </span>
                </td>
                <td class="border-dashed border-t border-gray-200 generated by">
                    <span class="text-gray-700 px-6 py-3 flex items-center">
                        {{ $block['generator']}} </span>
                    </span>
                </td>
                <td class="border-dashed border-t border-gray-200 forged">
                    <span class="text-gray-700 px-6 py-3 flex items-center">
                        {{ $block['forged']['total']}} </span>
                    </span>
                </td>
                <td class="border-dashed border-t border-gray-200 forged">
                    <span class="text-gray-700 px-6 py-3 flex items-center">
                        {{ $block['forged']['fee']}} </span>
                    </span>
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>
</div>





